baseURL = 'https://0xD3f3c7.github.io/0xD3f3c7-Blog/'
languageCode = 'en-us'
title = '0xD3f3c7'
theme = 'ananke'

[params]
  bg_color = "black"
  featured_image = "/images/abstract-bg.svg"
  description = "A blog on hacking, cybersecurity, and more."
  header_style = "animated"
  link_style = "hover"
